"""remove faculty field

Revision ID: 3aa515950545
Revises: cd7e6be0740c
Create Date: 2023-12-07 15:33:06.060603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa515950545'
down_revision = 'cd7e6be0740c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('faculty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty', sa.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
